name: 01 - Building Blocks
on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: I will not fail now
        run: exit 0
      - name: Say Goodbye
        run: |
          echo "Not failing this time"
          echo "Goodbye!"
