name: 04 - Using Actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run Unit Tests
        run: |
          npm run test

